version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: Tom
        UID: 1047256669
        MAIL: tom.martin@etu.univ-orleans.fr
        NAME: "MARTIN Tom"
    container_name: tom-martin-container
    volumes:
    - .:/var/www/html
    ports:
    - "8000:8000"
    environment:
      PHP_IDE_CONFIG: serverName=contacts
